# Generated by Django 4.0.1 on 2022-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubercontacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tubercontact',
            name='tuber_id',
        ),
        migrations.AlterField(
            model_name='tubercontact',
            name='user_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
