# Generated by Django 4.0.1 on 2022-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='invitelink',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
