# Generated by Django 4.0.1 on 2022-01-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_abouter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouter',
            name='photo',
            field=models.ImageField(upload_to='media/abouter/%Y/'),
        ),
    ]
